# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "master" => "192.168.33.10",
  "minion" => "192.168.33.11",
}

Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "ubuntu/trusty64"
      machine.vm.hostname = "%s.example.org" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 512]
      end
    end
    config.vm.provision "docker" do |d|
    end
  end
end
